### ISSUE TITLE
[PRIORITY HIGH] Crash SonarQube analysis

### ISSUE THREAD

**Issue by dedece35** [green-code-initiative/ecoCode#42]
**Describe the bug**
when we launch a SonarQube analysis, there is a lot of exception on ecocode plugin. Then, the analysis crashes and this stops and CI/CD pipeline.
please see examples above.

**To Reproduce**
JDK 17
Gradle
example command launched : `gradle --no-daemon sonarqube -Dsonar.qualitygate.wait=true -Dsonar.branch.name=release-4.1 -Pspring.test.config=/builds/contenu/rcc/rcc/.gradle/test.properties`
@dedece35 can give some example source code if need (to test it)

**Expected behavior**
Analysis in succes without exceptions.
Once correction OK, upgrade (if possible) SonarQube checks in code to avoid this kind of issue (make an audit of each rule to check Class Casts).

**Screenshots**
Please see log file.

**Software Versions**
 - SonarQube Version: 9.8 (build 63668)
 - Plugin Version: 0.2.1
 - JDK version : 17

**Comment by dedece35** [comment]
**Exception 1** : 
`Unable to run check class fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop - GSCIL on file 'solocal-rcc-server/src/main/java/com/solocal/rcc/service/filterchain/siret/SiretOrigineLienFilter.java', To help improve the SonarSource Java Analyzer, please report this problem to SonarSource: see https://community.sonarsource.com/
java.lang.ClassCastException: class org.sonar.java.model.statement.ForEachStatementImpl cannot be cast to class org.sonar.plugins.java.api.tree.ForStatementTree (org.sonar.java.model.statement.ForEachStatementImpl and org.sonar.plugins.java.api.tree.ForStatementTree are in unnamed module of loader org.sonar.classloader.ClassRealm @6e29edfd)
	at fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop.visitNode(AvoidGettingSizeCollectionInLoop.java:36)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$visit$6(VisitorsBridge.java:452)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$forEach$9(VisitorsBridge.java:468)
	at org.sonar.java.model.VisitorsBridge.runScanner(VisitorsBridge.java:265)`

**Exception 2** : 
`Unable to run check class fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop - GSCIL on file 'solocal-rcc-server/src/main/java/com/solocal/rcc/comptemanager/gateway/handlers/AbstractCommandHandler.java', To help improve the SonarSource Java Analyzer, please report this problem to SonarSource: see https://community.sonarsource.com/
java.lang.ClassCastException: class org.sonar.java.model.statement.ForEachStatementImpl cannot be cast to class org.sonar.plugins.java.api.tree.ForStatementTree (org.sonar.java.model.statement.ForEachStatementImpl and org.sonar.plugins.java.api.tree.ForStatementTree are in unnamed module of loader org.sonar.classloader.ClassRealm @6e29edfd)
	at fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop.visitNode(AvoidGettingSizeCollectionInLoop.java:36)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$visit$6(VisitorsBridge.java:452)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$forEach$9(VisitorsBridge.java:468)
	at org.sonar.java.model.VisitorsBridge.runScanner(VisitorsBridge.java:265)`

**Exception 3** : 
`Unable to run check class fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop - GSCIL on file 'solocal-rcc-server/src/main/java/com/solocal/rcc/checker/horaireexceptionnel/HoraireExceptionnelValidationChecker.java', To help improve the SonarSource Java Analyzer, please report this problem to SonarSource: see https://community.sonarsource.com/
java.lang.ClassCastException: class org.sonar.java.model.statement.WhileStatementTreeImpl cannot be cast to class org.sonar.plugins.java.api.tree.ForStatementTree (org.sonar.java.model.statement.WhileStatementTreeImpl and org.sonar.plugins.java.api.tree.ForStatementTree are in unnamed module of loader org.sonar.classloader.ClassRealm @6e29edfd)
	at fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop.visitNode(AvoidGettingSizeCollectionInLoop.java:36)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$visit$6(VisitorsBridge.java:452)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$forEach$9(VisitorsBridge.java:468)
	at org.sonar.java.model.VisitorsBridge.runScanner(VisitorsBridge.java:265)`

**Exception 4** : 
`Unable to run check class fr.cnumr.java.checks.UnnecessarilyAssignValuesToVariables - S63 on file 'solocal-rcc-server/src/main/java/com/solocal/rcc/script/horaireexceptionnel/HoraireExceptionnelMigrationService.java', To help improve the SonarSource Java Analyzer, please report this problem to SonarSource: see https://community.sonarsource.com/
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "org.sonar.plugins.java.api.tree.ReturnStatementTree.expression()" is null
	at fr.cnumr.java.checks.UnnecessarilyAssignValuesToVariables$CheckUseVariableVisitor.visitReturnStatement(UnnecessarilyAssignValuesToVariables.java:152)
	at org.sonar.java.model.statement.ReturnStatementTreeImpl.accept(ReturnStatementTreeImpl.java:70)
	at org.sonar.plugins.java.api.tree.BaseTreeVisitor.scan(BaseTreeVisitor.java:40)`

**Exception 5** : 
`Unable to run check class fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop - GSCIL on file 'solocal-rcc-server/src/main/java/com/solocal/rcc/service/notification/MessageNotificationFactory.java', To help improve the SonarSource Java Analyzer, please report this problem to SonarSource: see https://community.sonarsource.com/
java.lang.ClassCastException: class org.sonar.java.model.statement.ForEachStatementImpl cannot be cast to class org.sonar.plugins.java.api.tree.ForStatementTree (org.sonar.java.model.statement.ForEachStatementImpl and org.sonar.plugins.java.api.tree.ForStatementTree are in unnamed module of loader org.sonar.classloader.ClassRealm @6e29edfd)
	at fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop.visitNode(AvoidGettingSizeCollectionInLoop.java:36)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$visit$6(VisitorsBridge.java:452)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$forEach$9(VisitorsBridge.java:468)
	at org.sonar.java.model.VisitorsBridge.runScanner(VisitorsBridge.java:265)`

**Exception 6** : 
`Unable to run check class fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop - GSCIL on file 'solocal-rcc-server/src/main/java/com/solocal/rcc/comparator/ClassSpecificityComparator.java', To help improve the SonarSource Java Analyzer, please report this problem to SonarSource: see https://community.sonarsource.com/
java.lang.ClassCastException: class org.sonar.java.model.statement.WhileStatementTreeImpl cannot be cast to class org.sonar.plugins.java.api.tree.ForStatementTree (org.sonar.java.model.statement.WhileStatementTreeImpl and org.sonar.plugins.java.api.tree.ForStatementTree are in unnamed module of loader org.sonar.classloader.ClassRealm @6e29edfd)
	at fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop.visitNode(AvoidGettingSizeCollectionInLoop.java:36)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$visit$6(VisitorsBridge.java:452)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$forEach$9(VisitorsBridge.java:468)
	at org.sonar.java.model.VisitorsBridge.runScanner(VisitorsBridge.java:265)`

**Exception 7** : 
`Unable to run check class fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop - GSCIL on file 'solocal-rcc-server/src/main/java/com/solocal/rcc/alim/factory/QualibatFactory.java', To help improve the SonarSource Java Analyzer, please report this problem to SonarSource: see https://community.sonarsource.com/
java.lang.ClassCastException: class org.sonar.java.model.statement.ForEachStatementImpl cannot be cast to class org.sonar.plugins.java.api.tree.ForStatementTree (org.sonar.java.model.statement.ForEachStatementImpl and org.sonar.plugins.java.api.tree.ForStatementTree are in unnamed module of loader org.sonar.classloader.ClassRealm @6e29edfd)
	at fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop.visitNode(AvoidGettingSizeCollectionInLoop.java:36)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$visit$6(VisitorsBridge.java:452)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$forEach$9(VisitorsBridge.java:468)
	at org.sonar.java.model.VisitorsBridge.runScanner(VisitorsBridge.java:265)`

**Exception 8** : 
`Unable to run check class fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop - GSCIL on file 'solocal-rcc-server/src/main/java/com/solocal/rcc/service/liencontenu/LienContenuService.java', To help improve the SonarSource Java Analyzer, please report this problem to SonarSource: see https://community.sonarsource.com/
java.lang.ClassCastException: class org.sonar.java.model.statement.WhileStatementTreeImpl cannot be cast to class org.sonar.plugins.java.api.tree.ForStatementTree (org.sonar.java.model.statement.WhileStatementTreeImpl and org.sonar.plugins.java.api.tree.ForStatementTree are in unnamed module of loader org.sonar.classloader.ClassRealm @6e29edfd)
	at fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop.visitNode(AvoidGettingSizeCollectionInLoop.java:36)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$visit$6(VisitorsBridge.java:452)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$forEach$9(VisitorsBridge.java:468)
	at org.sonar.java.model.VisitorsBridge.runScanner(VisitorsBridge.java:265)`

**Exception 9** : 
`Unable to run check class fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop - GSCIL on file 'solocal-rcc-server/src/main/java/com/solocal/rcc/security/AzureSsoAuthenticationProvider.java', To help improve the SonarSource Java Analyzer, please report this problem to SonarSource: see https://community.sonarsource.com/
java.lang.ClassCastException: class org.sonar.java.model.statement.ForEachStatementImpl cannot be cast to class org.sonar.plugins.java.api.tree.ForStatementTree (org.sonar.java.model.statement.ForEachStatementImpl and org.sonar.plugins.java.api.tree.ForStatementTree are in unnamed module of loader org.sonar.classloader.ClassRealm @6e29edfd)
	at fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop.visitNode(AvoidGettingSizeCollectionInLoop.java:36)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$visit$6(VisitorsBridge.java:452)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$forEach$9(VisitorsBridge.java:468)
	at org.sonar.java.model.VisitorsBridge.runScanner(VisitorsBridge.java:265)`

**Exception 10** : 
`Unable to run check class fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop - GSCIL on file 'solocal-rcc-server/src/main/java/com/solocal/rcc/checker/intitule/IntituleNormalizationChecker.java', To help improve the SonarSource Java Analyzer, please report this problem to SonarSource: see https://community.sonarsource.com/
java.lang.ClassCastException: class org.sonar.java.model.statement.WhileStatementTreeImpl cannot be cast to class org.sonar.plugins.java.api.tree.ForStatementTree (org.sonar.java.model.statement.WhileStatementTreeImpl and org.sonar.plugins.java.api.tree.ForStatementTree are in unnamed module of loader org.sonar.classloader.ClassRealm @6e29edfd)
	at fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop.visitNode(AvoidGettingSizeCollectionInLoop.java:36)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$visit$6(VisitorsBridge.java:452)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$forEach$9(VisitorsBridge.java:468)
	at org.sonar.java.model.VisitorsBridge.runScanner(VisitorsBridge.java:265)`

**Exception 11** : 
`Unable to run check class fr.cnumr.java.checks.UnnecessarilyAssignValuesToVariables - S63 on file 'solocal-rcc-server/src/main/java/com/solocal/rcc/comptemanager/callback/LienContenuCreationCallback.java', To help improve the SonarSource Java Analyzer, please report this problem to SonarSource: see https://community.sonarsource.com/
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "org.sonar.plugins.java.api.tree.ReturnStatementTree.expression()" is null
	at fr.cnumr.java.checks.UnnecessarilyAssignValuesToVariables$CheckUseVariableVisitor.visitReturnStatement(UnnecessarilyAssignValuesToVariables.java:152)
	at org.sonar.java.model.statement.ReturnStatementTreeImpl.accept(ReturnStatementTreeImpl.java:70)
	at org.sonar.plugins.java.api.tree.BaseTreeVisitor.scan(BaseTreeVisitor.java:40)
	at org.sonar.plugins.java.api.tree.BaseTreeVisitor.scan(BaseTreeVisitor.java:34)`

**Exception 12** : 
`Unable to run check class fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop - GSCIL on file 'solocal-rcc-server/src/main/java/com/solocal/rcc/comptemanager/callback/UniqueContenuCallback.java', To help improve the SonarSource Java Analyzer, please report this problem to SonarSource: see https://community.sonarsource.com/
java.lang.ClassCastException: class org.sonar.java.model.statement.ForEachStatementImpl cannot be cast to class org.sonar.plugins.java.api.tree.ForStatementTree (org.sonar.java.model.statement.ForEachStatementImpl and org.sonar.plugins.java.api.tree.ForStatementTree are in unnamed module of loader org.sonar.classloader.ClassRealm @6e29edfd)
	at fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop.visitNode(AvoidGettingSizeCollectionInLoop.java:36)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$visit$6(VisitorsBridge.java:452)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$forEach$9(VisitorsBridge.java:468)
	at org.sonar.java.model.VisitorsBridge.runScanner(VisitorsBridge.java:265)`

**Exception 13** : 
`Unable to run check class fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop - GSCIL on file 'solocal-rcc-server/src/main/java/com/solocal/rcc/service/persistence/PersistenceService.java', To help improve the SonarSource Java Analyzer, please report this problem to SonarSource: see https://community.sonarsource.com/
java.lang.ClassCastException: class org.sonar.java.model.statement.WhileStatementTreeImpl cannot be cast to class org.sonar.plugins.java.api.tree.ForStatementTree (org.sonar.java.model.statement.WhileStatementTreeImpl and org.sonar.plugins.java.api.tree.ForStatementTree are in unnamed module of loader org.sonar.classloader.ClassRealm @6e29edfd)
	at fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop.visitNode(AvoidGettingSizeCollectionInLoop.java:36)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$visit$6(VisitorsBridge.java:452)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$forEach$9(VisitorsBridge.java:468)
	at org.sonar.java.model.VisitorsBridge.runScanner(VisitorsBridge.java:265)`

**Exception 14** : 
`Unable to run check class fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop - GSCIL on file 'solocal-rcc-server/src/main/java/com/solocal/rcc/service/search/provider/AbstractSearchProvider.java', To help improve the SonarSource Java Analyzer, please report this problem to SonarSource: see https://community.sonarsource.com/
java.lang.ClassCastException: class org.sonar.java.model.statement.ForEachStatementImpl cannot be cast to class org.sonar.plugins.java.api.tree.ForStatementTree (org.sonar.java.model.statement.ForEachStatementImpl and org.sonar.plugins.java.api.tree.ForStatementTree are in unnamed module of loader org.sonar.classloader.ClassRealm @6e29edfd)
	at fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop.visitNode(AvoidGettingSizeCollectionInLoop.java:36)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$visit$6(VisitorsBridge.java:452)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$forEach$9(VisitorsBridge.java:468)
	at org.sonar.java.model.VisitorsBridge.runScanner(VisitorsBridge.java:265)`

**Exception 15** (L2742) : 
`Unable to run check class fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop - GSCIL on file 'solocal-rcc-server/src/main/java/com/solocal/rcc/listener/IndexingListener.java', To help improve the SonarSource Java Analyzer, please report this problem to SonarSource: see https://community.sonarsource.com/
java.lang.ClassCastException: class org.sonar.java.model.statement.WhileStatementTreeImpl cannot be cast to class org.sonar.plugins.java.api.tree.ForStatementTree (org.sonar.java.model.statement.WhileStatementTreeImpl and org.sonar.plugins.java.api.tree.ForStatementTree are in unnamed module of loader org.sonar.classloader.ClassRealm @6e29edfd)
	at fr.cnumr.java.checks.AvoidGettingSizeCollectionInLoop.visitNode(AvoidGettingSizeCollectionInLoop.java:36)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$visit$6(VisitorsBridge.java:452)
	at org.sonar.java.model.VisitorsBridge$IssuableSubscriptionVisitorsRunner.lambda$forEach$9(VisitorsBridge.java:468)
	at org.sonar.java.model.VisitorsBridge.runScanner(VisitorsBridge.java:265)`

**Comment by dedece35** [comment]
**ANALYSIS**
all these exceptions are consequence of a lack in code : rule `AvoidGettingSizeCollectionInLoop ` is enabled for "foreach", "for" and "while" loops, but in the code only "for" loops are managed (with casting process). Thus, if a "while" loop or "foreach" loop appears, a casting exception is launched.

**CORRECTION**
- add "while" loop management
- disable "foreach" loop because we it's impossible to use code in condition loop (the foreach loop syntax is very strict)
- improve existing unit tests
- add new tests for "while" loops
- add new test for ignored "foreach" loops
